crits:
  build: .
  volumes:
    - ./dev/config:/config
    - ./docker:/docker
  links:
    - mongodb
  environment:
    - CRITS_INIT_DB=1
  ports:
    - "8080:8080"
mongodb:
  image: mongo:2.6
  command: mongod --quiet --nojournal --noprealloc --smallfiles
